name: Build and Deploy Staging
on: push
jobs:
  main:
    name: docs-staging.workerb.io
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@master
    - name: Yarn Install
      run: yarn install
    - name: Setup Environment
      run: |
        touch .env
        echo 'LOGIN_URL = "https://app-staging.workerb.io/"' > .env
        echo 'GA_ID = ${{ secrets.GA_ID }}' >> .env
    - name: Yarn Build
      run: yarn build
    - name: Yarn Export
      run: yarn export
    - name: Firebase Init
      run: yarn firebase use --token ${{ secrets.FIREBASE_TOKEN }} dev-docs-workerb-io
    - name: Deploy to Firebase
      run: yarn firebase deploy -m "Workflow $GITHUB_WORKFLOW, build $GITHUB_RUN_ID" --non-interactive --token ${{ secrets.FIREBASE_TOKEN }}
