name: Build and Deploy Stage
on:
  pull_request:
  workflow_dispatch:
    inputs:
      git-ref:
        description: Git Ref (Optional)
        required: false
jobs:
  main:
    name: stage
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@master
      - name: Yarn Install
        run: |
          git clone https://${{ secrets.GITLAB_TOKEN }}@gitlab.com/workerb/wb-editor.git
          sed -i -e 's/git+ssh:\/\/git@gitlab.com\/workerb\/wb-editor.git/file:\.\/wb-editor/g' ./package.json
          yarn install
      - name: Setup Environment
        run: |
          touch .env
          echo 'AMPLITUDE_KEY = ${{ secrets.STAGE_AMPLITUDE_KEY }}' > .env
          echo 'FE_URL = ${{ secrets.STAGE_LOGIN_URL }}' >> .env
          echo 'GA_ID = ${{ secrets.STAGE_GA_ID }}' >> .env
      - name: Yarn Build
        run: yarn build
      - name: Yarn Export
        run: yarn export
      - name: Deploy to Firebase
        run: |
          yarn firebase use --token ${{ secrets.FIREBASE_TOKEN }} ${{ secrets.STAGE_FIREBASE_PROJECT }}
          yarn firebase target:apply hosting docs docs-staging-workerb
          yarn firebase deploy -m "Workflow $GITHUB_WORKFLOW, build $GITHUB_RUN_ID" --non-interactive --token ${{ secrets.FIREBASE_TOKEN }}
