name: Build and Deploy Stage
on: pull_request
jobs:
  main:
    name: stage
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@master
    - name: Yarn Install
      run: yarn install
    - name: Setup Environment
      run: |
        touch .env
        echo 'LOGIN_URL = ${{ secrets.STAGE_LOGIN_URL }}' > .env
        echo 'GA_ID = ${{ secrets.STAGE_GA_ID }}' >> .env
    - name: Yarn Build
      run: yarn build
    - name: Yarn Export
      run: yarn export
    - name: Firebase Init
      run: yarn firebase use --token ${{ secrets.FIREBASE_TOKEN }} ${{ secrets.STAGE_FIREBASE_PROJECT }}
    - name: Deploy to Firebase
      run: yarn firebase deploy -m "Workflow $GITHUB_WORKFLOW, build $GITHUB_RUN_ID" --non-interactive --token ${{ secrets.FIREBASE_TOKEN }}
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2.0.0
      env:
        SLACK_ICON: https://github.com/quintessence/slack-icons/blob/master/images/github-logo-slack-icon.png
        SLACK_USERNAME: Github Actions
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}